server:
  port: 8080

file:
  input-folder: C:\Users\010184\Desktop\checking-folder

spring:
  application:
    name: panacea

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/panacea
    username: root
    password: secret

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  batch:
    jdbc:
      initialize-schema:

minio:
  url: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: my-bucket
